### ISSUE TITLE
Rating & Reviews System

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#32]

**Comment by KarineZhang** [comment]
-Users shall be able to evaluate the web application via rating star system & shall also be able to write a review of his/her experience with our web application. 
-By being able to see their comments, we can evaluate users' satisfaction and get some feedback from them in order to improve our web application in the future (evolution/maintenance wise).

**Comment by prich28** [comment]
This feature, though not yet fully functional has been added to the system with pull request #184.
