### ISSUE TITLE
#30 User can select a class to be removed from the list

### ISSUE THREAD

**Issue by patrickspensieri** [n2chao/SOEN341#47]
User Story:
User can select a class to be removed from the list of classes that are currently on their schedule or temporarily added to the list to be saved.

To track progress, refer to Epic #30

**Comment by prich28** [comment]
Assessed at the beginning of SPRINT2

Associated Tasks:
-Create front end for removing a course from pending list.

Difficulty:
5

Priority:
MED

Risk:
MED - This is to give the option of removing a class in the pending list in order to edit current class selections. Not being able to remove a class is not vital to the functioning of the entire site. However customization and error correction is important.

**Comment by patrickspensieri** [comment]
![issue47](https://cloud.githubusercontent.com/assets/8960233/24940560/df208a48-1f11-11e7-8663-fa4a40b166fd.jpg)
